apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-spark-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  hostPath:
    path: /data