apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-spark-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: data-spark-pv